build:
  maxIssues: 0
  excludeCorrectable: false
  weights:

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
  TooManyFunctions:
    active: true
    threshold: 20

style:
  active: true
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**']
  UnusedImports:
    active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
